---
title: "Did the COVID-19 pandemic increase Norwegian bankruptcies?"
author: "Olaf Ghanizadeh"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)

library(rvest)
#use httr so we can contruct URLs to query programatically
library(httr)
library(tidyverse)
library(lubridate)
library(ggplot2)
```

```{r scrape}
#A function to scrape brreg

#get the current date to fetch the lastest data for 2020
current_date <- format(Sys.Date(), "%d.%m.%Y")

brreg_scraper <- function(fromDate, toDate) {
  #brreg base URL
  url <- "https://w2.brreg.no/kunngjoring/kombisok.jsp?"
  #We can use the query argument from httr to create the URL to scrape, we do not add any further arguments than fromDate and toDate in this function, and the id_niva1 and id_niva2 is kept static to skip the need to filter for type of announcement
  query <- list(datoFra = fromDate, datoTil = toDate, id_niva1 = "51", id_niva2 = "56")
  #create the GET request that is later given to rvest
  resp <- GET(url, query=query) %>%
    read_html(.) %>%
    #get the first table
    html_nodes(xpath = "//table") %>%
    #but only the nested table
    html_nodes("table") %>%
    #let rvest create an R table from the data
    html_table() %>%
    #Store the table as a dataframe
    .[[1]] %>%
    #We only want companies, lets remove persons by filtering based on the org. nr. as the persons are listed with their Date of Birth and not org. nr. 
    #Let's select only the column with region name and date of announcement
    select(., X2, X4, X6) %>%
    rename(., "company"="X2", "orgnr" = "X4", "date" = "X6") %>%
    mutate(region=ifelse(grepl("[^Dato][A-Za-z]", date), date, NA)) %>% 
    fill(region) %>% 
    filter(orgnr != region, date != "") %>%
    filter(nchar(orgnr) > 6) %>%
    mutate(date = dmy(date)) %>%
    group_by(region, date=floor_date(date, "month")) %>%
    filter(region != "Utenlands") %>%
    summarise(count=cumsum(n())) %>%
    mutate("cumsum_region" = cumsum(count))
  }



```


```{r}
#Call functions for the two respective years. We the system returns only up until current date even if we set the toDate to a future date.
nineteen <- brreg_scraper("01.01.2019", "31.12.2019")
twenty <- brreg_scraper("01.01.2020", current_date)

```
```{r}
#Compiling the two dataframes into one for easier plotting
compiled <- rbind(nineteen,twenty) %>%
  group_by(year = factor(year(date))) %>%
  mutate(month = month(date, label = TRUE))

```


## Bankruptcies in 2019 versus 2020
In 2019 there were `r sum(nineteen$count)` reported bankruptcies in Norway, excluding private persons and foreign entities. For 2020 the number is `r sum(twenty$count)` YTD. The graph below gives a better picture of the situation:



```{r plot, results='hide', fig.width=12, fig.height=6, dev='svg'}

ggplot(compiled, aes(x = month, y = cumsum_region, group=year, color = year)) +
  geom_line() + 
  xlab("Month") + 
  ylab("Cumulative bankruptices per region") +
  facet_wrap(~ region, ncol = 3) +
  theme_minimal()
```

As of today, we cannot conclude that the ongoing pandemic has caused an increase in bankruptcies.